---
- name: Common | Update apt cache
  sudo: yes
  apt: update-cache=yes
  tags: common

- name: Common | Install git
  apt: pkg=git state=present
  sudo: yes
  tags: common

- name: Common | Install ruby
  apt: pkg=ruby
  sudo: yes
  tags: common

- name: Common | Install compass
  sudo: yes
  gem: name=compass
  tags: common
