---
- name: Node.js Install GNU-make
  sudo: yes
  command: apt-get install make

- name: Node.js Install g++
  sudo: yes
  command: apt-get install g++

- name: Node.js Download node.js
  command: wget http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz

- name: Extract node
  command: tar -xzf node-v0.10.21.tar.gz

- name: Configure, make install
  sudo: yes
  shell: cd ./node-v0.10.21;./configure;make;make install

