---
- hosts: servers
  gather_facts: false
  user: root

  tasks:
  - name: Pull source from github
    git: repo=${repo} dest=${src_root}

  - name: Build application
    command: cd ${src_root} && make build